### ISSUE TITLE
How that 'moodle/course:update' does not seem to be used?

### ISSUE THREAD

**Issue by mudrd8mz** [doiphode/moodle-block_bulkactivity#6]
The plugin does not seem to take the `'moodle/course:update'` capability into account at all. How do you then choose / filter / limit the target courses? The teacher typically has editing right in selected courses only.

**Comment by doiphode** [comment]
Resolved with 54b9a23d0d0557d5641867d360d1bb0f066540e3

**Comment by mudrd8mz** [comment]
So, as I see it. The block still shows all the courses as potential targets, and if the user chooses one he does not rights to, it ends up with an error? Should not it simply offer only the valid target courses?

**Comment by doiphode** [comment]
Thank you for reviewing this. I have just updated with the required capability.

014a69e54e765479c341c99f6e27669c0e65f992
